ENVIRONMENT:
    MAX_EPISODE_STEPS: 50
DATASET:
    TYPE: RearrangeDataset-v0
    SPLIT: train
    DATA_PATH: data/datasets/rearrange_pick/replica_cad/v0/{split}/{split}_counter_L_analysis_5000_500.json.gz
    SCENES_DIR: "data/replica_cad/"
TASK:
    TYPE: RearrangeReachTask-v0
    RENDER_TARGET: True
    EE_SAMPLE_FACTOR: 0.5

    JOINT_SENSOR:
        TYPE: "JointSensor"
        DIMENSIONALITY: 7
    RELATIVE_RESTING_POS_SENSOR:
        TYPE: "RelativeRestingPositionSensor"
    RESTING_POS_SENSOR:
        TYPE: "RestingPositionSensor"
    END_EFFECTOR_SENSOR:
        TYPE: "EEPositionSensor"
    SENSORS: ["JOINT_SENSOR", "RELATIVE_RESTING_POS_SENSOR", 'END_EFFECTOR_SENSOR', "RESTING_POS_SENSOR"]

    END_EFFECTOR_TO_REST_DISTANCE:
        TYPE: "EndEffectorToRestDistance"
    REARRANGE_REACH_REWARD:
        TYPE: "RearrangeReachReward"
        SCALE: 1.0
        DIFF_REWARD: True
    REARRANGE_REACH_SUCCESS:
        TYPE: "RearrangeReachSuccess"
        SUCC_THRESH: 0.1
    MEASUREMENTS:
        - "END_EFFECTOR_TO_REST_DISTANCE"
        - "REARRANGE_REACH_REWARD"
        - "REARRANGE_REACH_SUCCESS"
    ACTIONS:
        ARM_ACTION:
            TYPE: "ArmAction"
            ARM_CONTROLLER: "ArmRelPosAction"
            ARM_JOINT_DIMENSIONALITY: 7
            GRIP_CONTROLLER: null
            EE_CTRL_LIM: 0.025
            GRASP_THRESH_DIST: 0.15
            DELTA_POS_LIMIT: 0.025
            RENDER_EE_TARGET: True
    POSSIBLE_ACTIONS:
        - ARM_ACTION

SIMULATOR:
    ACTION_SPACE_CONFIG: v0
    AGENTS: ['AGENT_0']
    AGENT_0:
        ANGULAR_ACCELERATION: 12.56
        ANGULAR_FRICTION: 1.0
        COEFFICIENT_OF_RESTITUTION: 0.0
        HEIGHT: 1.5
        IS_SET_START_STATE: False
        LINEAR_ACCELERATION: 20.0
        LINEAR_FRICTION: 0.5
        MASS: 32.0
        RADIUS: 0.1
        SENSORS: ['HEAD_RGB_SENSOR', 'THIRD_RGB_SENSOR']
        START_POSITION: [0, 0, 0]
        START_ROTATION: [0, 0, 0, 1]
    HEAD_RGB_SENSOR:
        WIDTH: 128
        HEIGHT: 128
    THIRD_RGB_SENSOR:
        WIDTH: 512
        HEIGHT: 512

    # Agent setup
    ARM_REST: [0.6, 0.0, 0.9]
    CTRL_FREQ: 120.0
    AC_FREQ_RATIO: 4
    ROBOT_URDF: ./data/robots/hab_fetch/robots/hab_fetch.urdf
    FORWARD_STEP_SIZE: 0.25
    LAG_OBSERVATIONS: 0
    IK_ARM_URDF: null
    LOAD_OBJS: False

    # Grasping
    HOLD_THRESH: 0.09
    GRASP_IMPULSE: 1000.0

    DEFAULT_AGENT_ID: 0
    HABITAT_SIM_V0:
        ALLOW_SLIDING: True
        ENABLE_PHYSICS: True
        GPU_DEVICE_ID: 0
        GPU_GPU: False
        PHYSICS_CONFIG_FILE: ./data/default.physics_config.json
    SEED: 100
    SEMANTIC_SENSOR:
        HEIGHT: 480
        HFOV: 90
        ORIENTATION: [0.0, 0.0, 0.0]
        POSITION: [0, 1.25, 0]
        TYPE: HabitatSimSemanticSensor
        WIDTH: 640
    TILT_ANGLE: 15
    TURN_ANGLE: 10
    TYPE: RearrangeSim-v0
