aiocontextvars==0.2.2
aiohttp==3.8.1
aiosignal==1.2.0
alembic==1.7.4
appdirs==1.4.4
aria2p==0.10.4
asciimatics==1.13.0
astor==0.8.1
async-timeout==4.0.2
asynctest==0.13.0
beautifulsoup4==4.10.0
braceexpand==0.1.7
cachetools==4.2.4
charset-normalizer==2.0.7
click==8.0.3
cloudpickle==2.0.0
configparser==5.1.0
contextlib2==21.6.0
contextvars==2.4
decorator==4.4.2
dill==0.3.4
docker-pycreds==0.4.0
fastcore==1.3.27
filelock==3.4.1
frozenlist==1.2.0
fsspec==2021.11.1
future==0.18.2
gdown==4.3.0
git-archive-all==1.23.0
google-auth==2.3.3
google-auth-oauthlib==0.4.6
gym==0.21.0
habitat-sim==0.2.1
idna==3.3
idna-ssl==1.1.0
ifcfg==0.22
immutables==0.16
jax==0.2.17
joblib==1.1.0
kornia==0.6.1
lmdb==1.2.1
loguru==0.5.3
magnum==0.0.0
mako==1.1.5
markupsafe==2.0.1
moviepy==1.0.3
msgpack==1.0.2
multidict==5.2.0
multiprocess==0.70.12.2
oauthlib==3.1.1
objectio==0.2.29
omnidata-tools==0.0.12
opencv-python==4.5.4.58
opt-einsum==3.3.0
pandas==1.1.5
pathtools==0.1.2
pickle5==0.0.11
pillow==8.4.0
proglog==0.1.9
promise==2.3
psutil==5.8.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pydeprecate==0.3.1
pyfiglet==0.8.post1
pyperclip==1.8.2
pysocks==1.7.1
pytorch-lightning==1.5.6
pytz==2021.3
pyyaml==6.0
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.8
scikit-learn==0.24.2
sentry-sdk==1.4.3
shortuuid==1.0.7
simplejson==3.17.5
sklearn==0.0
soupsieve==2.3.1
sqlalchemy==1.3.24
submitit==1.4.0
subprocess32==3.5.4
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
termcolor==1.1.0
threadpoolctl==3.1.0
timm==0.4.12
torchmetrics==0.6.2
typer==0.4.0
urllib3==1.26.7
wandb==0.12.6
wcwidth==0.2.5
webdataset==0.1.40
websocket-client==1.2.1
yarl==1.7.2
yaspin==2.1.0
