BASE_TASK_CONFIG_PATH: configs/tasks/rearrange_reach_replica_cad.yaml

RL:
    REWARD_MEASURE: "rearrange_reach_reward"
    SUCCESS_MEASURE: "rearrange_reach_success"
    SUCCESS_REWARD: 10.0
    GYM_OBS_KEYS: ['joint', 'relative_resting_position']
    GYM_FIX_INFO_DICT: True
    GYM_ACTION_KEYS: ['ARM_ACTION']

ENV_NAME: "RearrangeRLEnv"
